### ISSUE TITLE
CCO Dashboard-Loading blocked by failures with other queries

### ISSUE THREAD

**Issue by madhukarmarri** [Azure/ccodashboard#215]
I have tried V2.4, 2.3, 2.2 and 2.1 . They all give the same error as the attached one. I did clear the credentials, entered mine. My PIM roles are active and have access to the data the needs to be pulled into the report. Need help with setting up the dashboard.

![CCODashboard_Errors](https://user-images.githubusercontent.com/94847356/142873839-db80ce32-f4c2-44f1-baeb-0e91e5896837.PNG)

**Comment by Thanayaby** [comment]
Vivtoriwjond

**Comment by Thanayaby** [comment]
CNN perniciousness

**Comment by lstire** [comment]
Same issue as madhukarmarri. Those particular queries cannot source the data. 

CC Get Entities
CC Blueprints
CC Published Blueprints
They all get the same error:
![image](https://user-images.githubusercontent.com/95202267/143819301-5b502497-2d7c-4d80-9ce7-e767d0e2cce3.png)
All the other queries work fine. Disable refresh on faulty queries  doesn't help to render the report and ignore faulty queries

**Comment by lstire** [comment]
Resolved!
I found that the folder structure must be the following regardless if PBI was downloaded from the App Store or not

C:\Users\xxxx\OneDrive - YYYYY\Documents\Power BI Desktop\Custom Connectors

And One Drive must be paused at the first refresh attempt! - it's documented but I ignored it

**Comment by madhukarmarri** [comment]
PBI was not downloaded from App store, rather its a .exe or .msi.
The .mez file is placed in the location mentioned in the deployment guide. I still get the same error.

**Comment by lstire** [comment]
I assume you saved it in:
 This PC>Documents\Power BI Desktop\Custom Connectors
Did you pause One Drive? I was necessary for me
I am happy to assist you if you are ok with sharing your email

**Comment by SpenCov101** [comment]
I get the same error. Connector is in the correct folder.
Downloaded from GIT folder.
Any ideas on how to resolve this?
Thanks in advance.

**Comment by lstire** [comment]
> 

Did you pause OneDrive?

**Comment by josunefon** [comment]
Its mandatory to use the path **C:\Users\xxxx\Documents\Power BI Desktop\Custom Connectors**, if we use the one drive folder probably Power BI will not recognize the custom connector
